<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <!--
================================================================================
    This file has been generated using the Trumpf WSO2 ESB Maven Archetype.
================================================================================
    -->
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.trumpf.esb.services.bill-of-materials</groupId>
		<artifactId>bill-of-materials</artifactId>
		<version>0.0.42</version>
	</parent>
	<artifactId>bill-of-materials-esb</artifactId>
	<version>0.0.42</version>
	<packaging>pom</packaging>
	<name>bill-of-materials ESB project</name>
	<description>bill-of-materials-esb ESB project</description>
	<build>
		<directory>target/capp</directory>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>xml-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<artifactId>maven-eclipse-plugin</artifactId>
				<configuration>
					<buildcommands/>
					<projectnatures>
						<projectnature>org.wso2.developerstudio.eclipse.esb.project.nature</projectnature>
					</projectnatures>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.wso2.maven</groupId>
				<artifactId>wso2-esb-api-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>com.sun.activation</groupId>
						<artifactId>javax.activation</artifactId>
						<version>1.2.0</version>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.wso2.maven</groupId>
				<artifactId>wso2-esb-task-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>com.sun.activation</groupId>
						<artifactId>javax.activation</artifactId>
						<version>1.2.0</version>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.wso2.maven</groupId>
				<artifactId>wso2-esb-proxy-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>com.sun.activation</groupId>
						<artifactId>javax.activation</artifactId>
						<version>1.2.0</version>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.wso2.maven</groupId>
				<artifactId>wso2-esb-sequence-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>com.sun.activation</groupId>
						<artifactId>javax.activation</artifactId>
						<version>1.2.0</version>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.wso2.maven</groupId>
				<artifactId>wso2-esb-localentry-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>com.sun.activation</groupId>
						<artifactId>javax.activation</artifactId>
						<version>1.2.0</version>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.wso2.maven</groupId>
				<artifactId>wso2-esb-template-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>com.sun.activation</groupId>
						<artifactId>javax.activation</artifactId>
						<version>1.2.0</version>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.wso2.maven</groupId>
				<artifactId>wso2-esb-endpoint-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>com.sun.activation</groupId>
						<artifactId>javax.activation</artifactId>
						<version>1.2.0</version>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
	</build>
	<properties>
		<CApp.type>bpel/workflow=zip,lib/registry/filter=jar,webapp/jaxws=war,lib/library/bundle=jar,service/dataservice=dbs,synapse/local-entry=xml,synapse/proxy-service=xml,carbon/application=car,registry/resource=zip,lib/dataservice/validator=jar,synapse/endpoint=xml,web/application=war,lib/carbon/ui=jar,service/axis2=aar,synapse/sequence=xml,synapse/configuration=xml,wso2/gadget=dar,lib/registry/handlers=jar,lib/synapse/mediator=jar,synapse/task=xml,synapse/api=xml,synapse/template=xml,synapse/message-store=xml,synapse/message-processors=xml</CApp.type>
		<maven.test.skip>false</maven.test.skip>
	</properties>
</project>
