<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <!--
================================================================================
    This file has been generated using the Trumpf WSO2 ESB Maven Archetype.
================================================================================
    -->
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>bill-of-materials</artifactId>
        <groupId>com.trumpf.esb.services.bill-of-materials</groupId>
        <version>0.0.42</version>
    </parent>
    <artifactId>bill-of-materials-car</artifactId>
    <groupId>com.trumpf.esb.services.bill-of-materials</groupId>
    <version>0.0.42</version>
    <packaging>carbon/application</packaging>
    <name>bill-of-materials CAR project</name>
    <description>bill-of-materials CAR Project containing CAR deployment artifact</description>
    <properties>
        <maven.car.deploy.skip>false</maven.car.deploy.skip>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-create-payload-seq>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-create-payload-seq>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-create-response-seq>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-create-response-seq>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-get-payload-seq>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-get-payload-seq>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-get-response-seq>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-get-response-seq>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-update-payload-seq>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-update-payload-seq>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-update-response-seq>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-update-response-seq>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-extend-materials-for-plant-payload-seq>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-extend-materials-for-plant-payload-seq>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-extend-materials-for-plant-response-seq>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-extend-materials-for-plant-response-seq>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-create-payload-transformation>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-create-payload-transformation>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-create-response-transformation>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-create-response-transformation>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-get-payload-transformation>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-get-payload-transformation>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-get-response-transformation>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-get-response-transformation>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-update-payload-transformation>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-update-payload-transformation>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-update-response-transformation>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-update-response-transformation>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-create-schema>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-create-schema>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-update-schema>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-update-schema>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-extend-materials-for-plant-schema>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-extend-materials-for-plant-schema>
        <com.trumpf.esb.services.bill-of-materials.api_._bill-of-materials-api>capp/EnterpriseServiceBus</com.trumpf.esb.services.bill-of-materials.api_._bill-of-materials-api>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-create-detailed-error-message>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-create-detailed-error-message>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-fault-seq>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-fault-seq>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-boms-get-payload-seq>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-boms-get-payload-seq>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-boms-get-response-seq>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-boms-get-response-seq>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-boms-get-payload-transformation>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-boms-get-payload-transformation>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-boms-get-response-transformation>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-boms-get-response-transformation>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-extend-materials-for-plant-payload-transformation>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-extend-materials-for-plant-payload-transformation>
        <com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-extend-materials-for-plant-response-transformation>capp/EnterpriseIntegrator</com.trumpf.esb.services.bill-of-materials.resource_._bill-of-materials-extend-materials-for-plant-response-transformation>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.api</groupId>
            <artifactId>bill-of-materials-api</artifactId>
            <version>${project.version}</version>
            <type>xml</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-fault-seq</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-update-response-transformation</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-create-detailed-error-message</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-update-payload-transformation</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-get-response-transformation</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-get-payload-transformation</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-create-response-transformation</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-create-payload-transformation</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-update-response-seq</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-update-payload-seq</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-get-response-seq</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-get-payload-seq</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-create-response-seq</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-create-payload-seq</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-extend-materials-for-plant-payload-seq</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-extend-materials-for-plant-response-seq</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-update-schema</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-create-schema</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-extend-materials-for-plant-schema</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-boms-get-response-seq</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-boms-get-payload-seq</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
         <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-boms-get-payload-transformation</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>   
         <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-boms-get-response-transformation</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-extend-materials-for-plant-payload-transformation</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.trumpf.esb.services.bill-of-materials.resource</groupId>
            <artifactId>bill-of-materials-extend-materials-for-plant-response-transformation</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-eclipse-plugin</artifactId>
                <configuration>
                    <buildcommands/>
                    <projectnatures>
                        <projectnature>org.wso2.developerstudio.eclipse.distribution.project.nature</projectnature>
                    </projectnatures>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.wso2.maven</groupId>
                <artifactId>maven-car-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.wso2.maven</groupId>
                <artifactId>maven-car-deploy-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>mock</id>
            <build>
                <finalName>${project.artifactId}</finalName>
                <plugins>
                    <plugin>
                        <groupId>org.wso2.maven</groupId>
                        <artifactId>maven-car-deploy-plugin</artifactId>
                        <version>${maven-car-deploy-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>deployThisCar</id>
                                <phase>pre-integration-test</phase>
                                <goals>
                                    <goal>deploy-car</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
